version: '3'

services:
  testsmtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
    networks:
      main:
  ifxmail-db:
    image: mariadb
    volumes:
      - ifxmail-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ifxmail
      - MYSQL_DATABASE=ifxmail
      - MYSQL_USER=ifxmail
      - MYSQL_PASSWORD=ifxmail
      - TZ=America/New_York
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      main:
  ifxmail:
    image: ifxmail
    volumes:
      - ../../ifxmail:/app
    environment:
      - IFXMAIL_USERNAME=root
      - IFXMAIL_PASSWORD=ifxmail
      - IFXMAIL_HOSTNAME=ifxmail-db
      - IFXMAIL_DATABASE=ifxmail
      - IFX_REMOTE_USER=veradmin
      - IFXMAIL_SMTP_SERVER=testsmtp:25
      - IFXMAIL_LOGLEVEL=INFO
      - IFXMAIL_DEBUG=TRUE
      - PYTHONUNBUFFERED=1
    links:
      - ifxmail-db
    depends_on:
      - ifxmail-db
    ports:
      - 6969:80
    networks:
      main:
  ifxmail-runner:
    image: ifxmail
    command: ./wait-for-it.sh -t 120 ifxmail-db:3306 -- ./manage.py processQueue testsmtp
    volumes:
      - ../../ifxmail:/app
    environment:
      - IFXMAIL_USERNAME=ifxmail
      - IFXMAIL_PASSWORD=ifxmail
      - IFXMAIL_HOSTNAME=ifxmail-db
      - IFXMAIL_DATABASE=ifxmail
      - IFX_REMOTE_USER=veradmin
      - IFXMAIL_SMTP_SERVER=testsmtp
      - IFXMAIL_LOGLEVEL=INFO
    links:
      - ifxmail-db
      - testsmtp
    depends_on:
      - ifxmail-db
      - testsmtp
    networks:
      main:
  nanites-db:
    image: mariadb
    volumes:
      - nanites-test-data:/var/lib/mysql
#      - nanites-prod-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nanites
      - MYSQL_DATABASE=nanites
      - MYSQL_USER=nanites
      - MYSQL_PASSWORD=nanites
    ports:
      - 3360:3306
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      main:
  nanites:
    image: nanites
    volumes:
      - ../../nanites:/app
    environment:
      - NANITES_USERNAME=nanites
      - NANITES_PASSWORD=nanites
      - NANITES_HOSTNAME=nanites-db
      - NANITES_DATABASE=nanites
      - IFX_REMOTE_USER=veradmin
      - NANITES_DEBUG=TRUE
      - NANITES_LOGLEVEL=DEBUG
    links:
      - nanites-db
    depends_on:
      - nanites-db
    ports:
      - 8765:80
    networks:
      main:
  coldfront-db:
    image: mariadb
    volumes:
      - coldfront-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coldfront
      - MYSQL_DATABASE=coldfront
      - MYSQL_USER=coldfront
      - MYSQL_PASSWORD=coldfront
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      main:
  coldfront:
    image: coldfront
    depends_on:
      - coldfront-db
      - nanites
      - fiine-drf
    volumes:
      - ../../coldfront2:/usr/src/app
    links:
      - testsmtp
      - fiine-drf
    ports:
      - 9022:80
    environment:
      - COLDFRONT_IFX_APP_TOKEN=b3b3a090a553dd6bcb29c9bfec7fb7704dee1ccc
      - SMTP_SERVER=testsmtp
      - IFX_REMOTE_USER=veradmin
      - NANITES_API_BASE=http://nanites/nanites/api
      - IFXMAIL_API_BASE=http://ifxmail/ifxmail/api
      - FIINE_API_BASE=http://fiine-drf/fiine/api
      - PYTHONUNBUFFERED=1
    networks:
      main:

