# Generated by Django 4.2.14 on 2026-09-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_historicalproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectuser',
            name='primary_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='primary_group',
            field=models.BooleanField(default=False),
        ),
    ]
