name: Coldfront CI

on:
  push:
    branches: [ "cp_cicd", "development" ]
  pull_request:
    branches: [ "cp_cicd", "development" ]

env:
  GITHUB_IFX_URL: https://ifx:${{ secrets.IFX_GITLAB_DEPLOY_TOKEN }}@gitlab-int.rc.fas.harvard.edu/informatics
  IFXURLS_COMMIT: 549af42dbe83d07b12dd37055a5ec6368d4b649
  NANITES_CLIENT_COMMIT: 1e67ce787e27c9c0e32a4c97a4967c297d30b7cf
  IFXUSER_COMMIT: 6b7194698b49550ae6df395cfea96380536a41bc
  IFXMAIL_CLIENT_COMMIT: 8f728ff54441d2f2449fd3c31b75f0f77372b5f2
  FIINE_CLIENT_COMMIT: 1946c8db410077d374b8b16f6de5199d9ed10d7e
  IFXEC_COMMIT: 0c09c90890fb87d4db22c635a6c403c89e1a957f
  IFXBILLING_COMMIT: c19aa7fd4a57a74a76d42c1595165c56128b36b0

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Configure SSH
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.ACTION_SSH }}
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/staging.key
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+ssh://git@github.com/harvardinformatics/ifxmail.client.git@$IFXMAIL_CLIENT_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/ifxurls.git@$IFXURLS_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/fiine.client.git@$FIINE_CLIENT_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/ifxec.git@$IFXEC_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/ifxbilling.git@$IFXBILLING_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/nanites.client.git@$NANITES_CLIENT_COMMIT && \
        pip install git+ssh://git@github.com/harvardinformatics/ifxuser.git@$IFXUSER_COMMIT && \
        pip install ldap3 django_auth_ldap && \
        pip install -r requirements.txt
    # - name: Format with black
    #   run: |
    #     pip install black
    #     # format the files with black
    #     black .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Sort imports
      run: |
        pip install isort
        # stop the build if there are Python syntax errors or undefined names
        isort .
        isort --check --diff .
    # - name: Build the images and start the containers
    #   run: |
    #     export GITHUB_WORKFLOW=True
    #     export MODE="Test"
    #     docker-compose -f docker-compose.yml build
    #     docker-compose -f docker-compose.yml up -d
    #     # run: docker-compose up -d --build
    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down
    - name: Run Tests
      run: |
        python manage.py test
